services:
  nginx:
    image: nginx:stable
    volumes:
      - '.:/srv'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
    depends_on:
      - php
  php:
    build: ./docker/php
    depends_on:
      - db
    volumes:
      - '.:/srv'
  db:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data:rw
volumes:
  db_data:
